<?php 
    $redis = new Redis();
    $redis->connect('127.0.0.1',6379);
    $docid = $redis-.get("loginid");
    $conn = new mysqli("localhost","root","","guvi");
     $stmt = $conn->prepare("SELECT * FROM Login WHERE email = ?");
        $stmt->bind_param("s", $Email);
        $Email = $cred->Email;
        $stmt->execute();
        $stmt = $conn->prepare("SELECT * FROM Login WHERE Name = ?");
        $stmt->bind_param("s", $Name);
        $Name = $cred->Name;
        $stmt->execute();
        $stmt = $conn->prepare("SELECT * FROM Login WHERE Password = ?");
        $stmt->bind_param("s", $Password);
        $Password = $cred->Password;
        $stmt->execute();
        $stmt = $conn->prepare("SELECT * FROM Login WHERE Phone= ?");
        $stmt->bind_param("s", $Phone);
        $Phone = $cred->Phone;
        $stmt->execute();
        $stmt = $conn->prepare("SELECT * FROM Login WHERE Gender = ?");
        $stmt->bind_param("s", $Gender);
        $Gender= $cred->Gender;
        $stmt->execute();
        $stmt = $conn->prepare("SELECT * FROM Login WHERE Language = ?");
        $stmt->bind_param("s", $Language);
        $Language= $cred->Language;
        $stmt->execute();
        $stmt = $conn->prepare("SELECT * FROM Login WHERE State = ?");
        $stmt->bind_param("s", $State);
        $State = $cred->State;
        $stmt->execute();
        $stmt = $conn->prepare("SELECT * FROM Login WHERE City = ?");
        $stmt->bind_param("s", $City);
        $City = $cred->City;
        $stmt->execute();
        $stmt = $conn->prepare("SELECT * FROM Login WHERE Postal = ?");
        $stmt->bind_param("s", $Postal);
        $Postal = $cred->Postal;
        $stmt->execute();
        $stmt = $conn->prepare("SELECT * FROM Login WHERE About = ?");
        $stmt->bind_param("s", $About);
        $About = $cred->About;
        $stmt->execute();
        
        $result = $stmt->get_result();
        $resultset = $result->fetch_assoc();
        echo 1;
    echo "<script>\n";
    echo " let doc = ".$resultset;
    echo "</script>";
    include(_DIR_."\..\profile.html");
?>